#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below requirements
# localhost is 127.0.0.2 and facebook.com is 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
